In [1]:
a<-5

name<- c("Turan", "Laman", "Ravan")
age<- c(29, 23, 22)
gender<-c("M", "F", "M")

In [2]:
friends<-data.frame(name, age, gender)

friends

  name  age gender
1 Turan 29  M
2 Laman 23  F
3 Ravan 22  M

In [3]:
friends[1:2,1]

[1] "Turan" "Laman"

In [4]:
friends[friends$age<25, 1:2]

  name  age
2 Laman 23
3 Ravan 22

In [5]:
library(dplyr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [10]:
friends %>%
    select(name, age) %>%
    filter(age < 25)

  name  age
1 Laman 23
2 Ravan 22

In [11]:
df<-read.csv("/kaggle/input/datasets/prathamsharma123/formula-1-fantasy-2021/azerbaijan_constructor_performance.csv")

In [12]:
head(df)

  Constructor.Name Fantasy.Points Driver.1.Qualifying.Position
1 Mercedes          9              2
2 Red Bull         45              3
3 McLaren          40              6
4 Ferrari          28              1
5 Aston Martin     31             11
6 Alpine           20              9
  Driver.2.Qualifying.Position Driver.1.Race.Finish Driver.2.Race.Finish
1 10                           12                   15
2 7                             1                   DNF
3 13                            5                   9
4 5                             4                   8
5 NC                            2                   DNF
6 12                            6                   DNF

In [30]:
df %>%
    select(Constructor.Name, Driver.1.Race.Finish, Driver.2.Race.Finish) %>%
    filter(Constructor.Name == "Ferrari" | Constructor.Name == "Red Bull")%>%
    mutate(Driver.1.Race.Finish = Driver.1.Race.Finish / 10)

# || checks only the first element, ignores the rest. But we need to consider all here
# So, || will give an error.

  Constructor.Name Driver.1.Race.Finish Driver.2.Race.Finish
1 Red Bull         0.1                  DNF
2 Ferrari          0.4                  8